/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package testproject;
import javax.swing.*;
import java.util.*;
import java.io.*;
import java.util.Date; 
/**
 *
 * @author khale
 */
public class CreditCard extends javax.swing.JFrame {

    /**
     * Creates new form CreditCard
     */
    int selectedIndex;
    ArrayList<User> users;
    ArrayList<Normal> normals;
    ArrayList<VIP>  vips;
    int lastNormalIndex=-1;
    public CreditCard() {
        initComponents();
        users = new ArrayList<User>();
        normals = new ArrayList<Normal>();
        vips = new ArrayList<VIP>();
        populateArrayList();
        String [] names = new String[normals.size()+vips.size()];
        int j=0;
        for(int i=0;i<normals.size();i++){
            names[j]=normals.get(i).getName();
            j++;
            lastNormalIndex=i;
        }
        for(int i=0;i<vips.size();i++){
            names[j]=(vips.get(i).getName());
            j++;
        }
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(names));
        jComboBox1.setSelectedIndex(0);
        
    }
    
    public void populateArrayList(){
        //file el normals bada2
        try {
            FileInputStream normFile = new FileInputStream("norm2.dat");
            ObjectInputStream normInputFile = new ObjectInputStream(normFile);
            boolean endOfFile= false;
            while(!endOfFile){
                try{
                    normals.add((Normal)normInputFile.readObject());
                }
                catch(EOFException e){
                    endOfFile = true;
                }
                catch(Exception f){
                   JOptionPane.showMessageDialog(null,f.getMessage());
               }
            }
            normInputFile.close();           
        }
        catch(IOException e) {
            JOptionPane.showMessageDialog(null,e.getMessage());           
        }
        //file el vips bada2
        try {
            FileInputStream vipFile = new FileInputStream("vip2.dat");
            ObjectInputStream vipInputFile = new ObjectInputStream(vipFile);
            boolean endOfFile= false;
            while(!endOfFile){
                try{
                    vips.add((VIP)vipInputFile.readObject());
                }
                catch(EOFException e){
                    endOfFile = true;
                }
                catch(Exception f){
                   JOptionPane.showMessageDialog(null,f.getMessage());
               }
            }
            vipInputFile.close();           
        }
        catch(IOException e) {
            JOptionPane.showMessageDialog(null,e.getMessage());           
        }
        //file el user combined 
        /*try {
            FileInputStream userFile = new FileInputStream("user.dat");
            ObjectInputStream userInputFile = new ObjectInputStream(userFile);
            boolean endOfFile= false;
            while(!endOfFile){
                try{
                    users.add((User)userInputFile.readObject());
                }
                catch(EOFException e){
                    endOfFile = true;
                }
                catch(Exception f){
                   JOptionPane.showMessageDialog(null,f.getMessage());
               }
            }
            userInputFile.close();           
        }
        catch(IOException e) {
            JOptionPane.showMessageDialog(null,e.getMessage());           
        }*/
    }
    
    public void saveUsersToFile(){
        try{
            FileOutputStream normFile = new FileOutputStream("norm2.dat");
            ObjectOutputStream normOutputFile = new ObjectOutputStream(normFile);
            for(int i=0;i<normals.size();i++){
                normOutputFile.writeObject(normals.get(i));
            }
            normOutputFile.close();
            //JOptionPane.showMessageDialog(null,"Successfully Saved");
            this.dispose();
        }
        catch(IOException e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
        try{
            FileOutputStream vipFile = new FileOutputStream("vip2.dat");
            ObjectOutputStream vipOutputFile = new ObjectOutputStream(vipFile);
            for(int i=0;i<vips.size();i++){
                vipOutputFile.writeObject(vips.get(i));
            }
            vipOutputFile.close();
            JOptionPane.showMessageDialog(null,"Successfully Saved");
            this.dispose();
        }
        catch(IOException e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Name");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Credit Card Balance");

        jTextField1.setEditable(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Price");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Password");

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox1, 0, 222, Short.MAX_VALUE)
                    .addComponent(jTextField1)
                    .addComponent(jTextField3)
                    .addComponent(jTextField4))
                .addContainerGap(144, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        selectedIndex = jComboBox1.getSelectedIndex();
        if(selectedIndex >lastNormalIndex){
            
            jTextField1.setText(vips.get(selectedIndex-lastNormalIndex-1).getMaxLimit()+"");
        }else{
            
            jTextField1.setText(normals.get(selectedIndex).getMaxLimit()+"");
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(selectedIndex >lastNormalIndex && !jTextField4.getText().equals(vips.get(selectedIndex-lastNormalIndex-1).getPassword()) && !jTextField4.getText().trim().equals("Admin") ){
            JOptionPane.showMessageDialog(null, "Incorrect Password");
            //this.dispose();
            
        } else if(selectedIndex <=lastNormalIndex && !jTextField4.getText().equals(normals.get(selectedIndex).getPassword()) && !jTextField4.getText().trim().equals("Admin") ){
            JOptionPane.showMessageDialog(null, "Incorrect Password");
        
        }else {
            Double price = Double.parseDouble(jTextField3.getText().trim());
            Date date = new Date();
            if(selectedIndex>lastNormalIndex){
                vips.get(selectedIndex-lastNormalIndex-1).creditCard(price);
                vips.get(selectedIndex-lastNormalIndex-1).setDateOfPurchase(date);
            }else{
                normals.get(selectedIndex).creditCard(price);
                normals.get(selectedIndex).setDateOfPurchase(date);
            }
            
            saveUsersToFile();
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreditCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreditCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreditCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreditCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreditCard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
